#!/bin/bash

 
   # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
   #                                                                                                 #
   #   R R R R R                                                                                     #
   #   R        R                             d   0 0 0 0                 !!!             3 3 3 3    #
   #   R        R                             d  0      00                ! !                    3   #
   #   R        R                             d  0     0 0                ! !                    3   #
   #   R R R R R         a                    d  0    0  0                ! !                    3   #
   #   R   R       a a a a  n n n n    d d d d   0   0   0  m  m m  m m   ! !  z z z z z    3 3 3    #
   #   R    R     a      a  nn     n  d       d  0  0    0  m m   m    m  !!!        z           3   #
   #   R     R    a      a  n      n  d       d  0 0     0  m     m    m           z             3   #
   #   R      R   a      a  n      n  d       d  00      0  m     m    m  !!!    z               3   #
   #   R       R   a a a a  n      n   d d d d    0 0 0 0   m     m    m  !!!  z z z z z  3 3 3 3    #
   #                                                                                                 # 
   #                                                                                                 #
   #      M             M   3 3 3 3         K       K                           N         N  !!!     #
   #      MM           MM          3        K     K                         //  N N       N  ! !     #
   #      M M         M M          3        K   K                          //   N  N      N  ! !     #
   #      M  M       M  M          3        K K               a           //    N   N     N  ! !     #
   #      M   M     M   M     3 3 3         KK          a a a a  p p p p        N    N    N  ! !     #
   #      M    M   M    M          3        K K        a      a  p      p       N     N   N  !!!     #
   #      M     M M     M          3        K   K      a      a  p      p       N      N  N          #
   #      M      M      M          3        K     K    a      a  p      p       N       N N  !!!     #
   #      M             M   3 3 3 3         K       K   a a a a  p p p p        N         N  !!!     #
   #                                                             p                                   #
   #                                                             p                                   # 
   #                                                             p                                   #
   #                                                             p                                   #
   #                                                                                                 #
   # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 




#Print "Please Enter to Proceed"
echo 'Please Enter to Proceed'

#Initiate admin access so that programs do not require further input of user account's password
#Print "Thank You" 
sudo echo 'Thank You'

#Check to see what connections are up
#ie what adapters are currently working
adapter=$(ip -o link show | awk '/state UP/{ gsub("\:",""); print $2}')

#Print active adapter's name
echo "Here Is My Connected Adapter's Name: "$adapter

#Get SSID of currently connected wireless network
SSID=$(iwgetid -r)

#Print "Here Is My Connected SSID"
echo 'Here Is My Connected SSID: '$SSID

#Grabs the BSSID for the currently connected wireless network
BSSIDdirty=$(sudo awk 'NR == 13' /etc/NetworkManager/system-connections/$SSID) #~/Programs/Scripts/bin/D2D7B1)

#Prints "This Is the Dirty BSSID :" and BSSIDdirty variable
#echo 'This Is the Dirty BSSID: '$BSSIDdirty

#This is to clean up the dirty BSSID so that it is readable by future programs as input
BSSIDclean=$(echo $BSSIDdirty | awk -F"=" '{print $2}' | awk -F";" '{print $1}')

#Print "This Is The BSSID: " and BSSID variable
echo 'This Is The BSSID: '$BSSIDclean

#Grabs the PSK ie password for the currently connected wireless network
PSKdirty=$(sudo awk 'NR == 18' /etc/NetworkManager/system-connections/$SSID)

#Print "This Is The Dirty PSK: " and PSKdirty variable
#echo this is the PSKdirty $PSKdirty

#This is to clean up the dirty PSK so that it is readable by future programs as input
PSKclean=$(echo $PSKdirty | awk -F"=" '{print $2}')

#Print "This Is The PSK: " and PSK variable
echo 'This Is The PSK: '$PSKclean

#Disconnect from network
nmcli d disconnect $adapter

#Stop Network-Manager Service
sudo service network-manager stop
echo 'Network-Manager Service Stop'
sleep 0.1

#Stop Network Service
sudo service networking stop
echo 'Network Service Stop'
sleep 0.1

#Randomize Me Kap'n! aka "RMK" works fine without initializing this command
#macchanger start

#Randomize Mac Address With Same Vendor
sudo macchanger -a $adapter

#Randomize Me Kap'n! aka "RMK" works fine without initializing this command
#macchanger stop

#Start Network-Manager Service
sudo service network-manager start
echo 'Network-Manager Service Start'
sleep 0.8

#Start Networking Service
sudo service networking start
echo 'Network Service Start'
sleep 3

#Connect to previously connected wireless network
nmcli d wifi connect $BSSIDclean password $PSKclean

#Windscribe VPN connects
#Will automatically connect to US-East if othe location is not spedicifed
#Do not enable this option if you do not have a Windscribe VPN account
#windscribe connecto




#Extra command that is not in use, it is nice to know if needing statistics display for wifi
#nmcli -f in-use,ssid,bssid,signal,bars  dev wifi
